<?php
/**
 * @file
 * realtor_user.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function realtor_user_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'CA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '06340cee-bc96-45a1-9295-fadd445f0fac',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'RSPS',
    'description' => 'Resort & Second-Home Property Specialist / RSPS',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '096f6c06-f759-4bc7-909e-2a4e30aaab40',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'PROVENCE-ALPES-COTE D\'AZUR',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '12b9933a-95f8-447a-8a9f-f13e5bbffae5',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'NB',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '13f6dfc1-c574-4b1b-b5a7-4bbb35e65b7c',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'BZ',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '15a9a5e4-6c91-400f-8bbe-d5ca4b909e0f',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'SIOR',
    'description' => 'Society of Industrial and Office REALTORS® / SIOR®',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '188850a0-1d4f-4408-b918-e716b7e5b385',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'BO',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1a2fa6e3-8561-4dcb-a62f-45e894388f28',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'IL',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2194200e-e121-4851-b400-265a570ad69e',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'ON',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2545f45a-ebe8-4b33-b77b-b72e588cbac5',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'Printer',
    'description' => 'Printer: quick printer, offset printer; business cards, banners, flyers',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '2704b66e-00e1-46d1-874f-890815a10071',
    'vocabulary_machine_name' => 'company_type',
  );
  $terms[] = array(
    'name' => 'France',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '399f83f4-d2a0-4ded-8ace-c76f135d8c88',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'NSW',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3fa93fd7-ee40-453a-bd15-79f8ff791c53',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'SRES',
    'description' => 'Seniors Real Estate Specialist®, SRES®',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4173f93c-5d61-4b7c-9c24-857f91825b23',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'AL',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4178d20e-4ef8-43c5-876e-6fac769eb61d',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'Builder',
    'description' => 'Builder',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '4521d706-4990-4638-b3f7-37a33f54d0a7',
    'vocabulary_machine_name' => 'company_type',
  );
  $terms[] = array(
    'name' => 'OV',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4938b8b5-704a-4520-9462-3096c2781bc6',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'PZ',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4a4b3a96-2a9e-45ca-a618-619079e60320',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'Internet Service Provider',
    'description' => 'Website Hosting, DSL or Dialup connection; email',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '4c2b0ec4-75b2-462d-9597-22a1861ee59e',
    'vocabulary_machine_name' => 'company_type',
  );
  $terms[] = array(
    'name' => 'UT',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4c351989-eea0-4651-a1a7-354895585b4a',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'Oregon',
    'description' => 'Oregon',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '50d803de-de6d-421d-a041-e5dbb1a0267b',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'EN',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '527e9209-394c-440a-a9b0-9e4e39e23a5f',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'PMN',
    'description' => 'Performance Management Network / PMN',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '528c39f9-7228-4c1d-a8e5-aaee4416ef82',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'ILE-DE-FRANCE',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '571b1fb2-a438-468a-8b72-133488ce7742',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'CPM',
    'description' => 'Certified Property Manager / CPM®',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5881cae4-db30-4184-8390-e7dd646861ad',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'LI',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '59beb4f6-ab94-4f13-badf-91cbd933577c',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'RAA',
    'description' => 'Residential Accredited Appraiser / RAA(sm)',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5a1b63d7-2129-4e14-a999-e33c1af2c55d',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'SFR',
    'description' => 'Short Sales & Foreclosures Resource / SFR',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5a5694c5-a5e4-48d5-9642-df4e0fdef9c0',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'CRE',
    'description' => 'Counselor of Real Estate / CRE®',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5c727efd-3c53-486d-a094-c7d36f35e8d7',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'NI',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '60911157-ba33-485a-9593-983d85d0909a',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'TX',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6903789a-99fc-4f87-a6a3-df790ba60dad',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'GE',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '693978e2-4ccd-4926-9c31-27587542f92a',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'CRB',
    'description' => 'Certified Real Estate Brokerage Manager / CRB(sm)',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '69865bec-fc68-4de3-8e6b-f55daf1b34f6',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'WA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6e8d9850-8d77-4c73-afd9-a401b956c7ca',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'RP',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '70a8ef15-575c-48c6-a460-f8718d47a5dc',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'GRI',
    'description' => 'Graduate, REALTOR® Institute / GRI(sm)',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '713e3e5c-945b-4424-a722-c2d69967c663',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'BPOR',
    'description' => 'Broker Price Opinion Resource (BPOR)',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7eb4c4ba-382d-486b-a9ac-a6061afaa70d',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'RCE',
    'description' => 'REALTOR® Association Certified Executive / RCE',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '832e36b0-07d7-42d1-a16c-8ced05b6ac40',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'Flyer1',
    'description' => 'New flyer, main pic + first three from the gallery.',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8f2c1bde-cdb9-4789-bc45-7c0ac88384b3',
    'vocabulary_machine_name' => 'flyers',
    'field_flyer_label' => array(
      'und' => array(
        0 => array(
          'value' => 'flyer1',
          'format' => NULL,
          'safe_value' => 'flyer1',
        ),
      ),
    ),
    'field_flyer_image' => array(),
    'field_required_images' => array(
      'und' => array(
        0 => array(
          'value' => 4,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'GAA',
    'description' => 'General Accredited Appraiser, GAA(sm)',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9173c6b9-3b16-4b45-9104-7ea3fd2f1c38',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'Real Estate',
    'description' => 'Real Estate Agent or Agency',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '93e1a465-c5dd-4cb1-b2ed-f8a0dff740e1',
    'vocabulary_machine_name' => 'company_type',
  );
  $terms[] = array(
    'name' => 'BY',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '994609f0-7d76-41a4-ae7f-f1d3e4fbff5c',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'CIPS',
    'description' => 'Certified International Property Specialist / CIPS®',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '99ae59e9-3b2d-4268-a1fc-0c1dd16bbc9d',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'BW',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9a67978f-d956-4975-852a-b2c0de6c68ae',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'ALC',
    'description' => 'Accredited Land Consultant / ALC(sm)',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9b3ef013-57d4-404e-854f-641af9c58e66',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'BG',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9f81e71d-3a2d-4fbd-b230-25483b6d17a2',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'VA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a0ebd4cf-66f8-4fa4-8a2d-3ef928dbf51d',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'CO',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a1f939e6-cfc9-4a59-9899-affd342cea40',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'AHWS',
    'description' => 'At Home with Diversity / AHWD',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a2bcb6e5-8d9c-408a-a9d9-381685a033ef',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'STYRIA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a59d94e8-bb7b-47fe-a7d1-a39dc564695f',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'Classic Flyer',
    'description' => 'Classic Flyer, displayed through the view "Listing - Classic Flyer" and on the URL /flyer/classic/{listing title}',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a7e5fe57-f8df-47c2-8f74-9472b5f8f244',
    'vocabulary_machine_name' => 'flyers',
    'field_flyer_label' => array(
      'und' => array(
        0 => array(
          'value' => 'classic',
          'format' => NULL,
          'safe_value' => 'classic',
        ),
      ),
    ),
    'field_flyer_image' => array(),
    'field_required_images' => array(),
  );
  $terms[] = array(
    'name' => 'MI',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b79ed389-24c9-4b63-bce3-8cac620bdba8',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'CRS',
    'description' => 'Certified Residential Specialist® / CRS®',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b7a8c75d-1b88-42d9-b15e-2d61cefbd3e5',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'Rental Management',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b7cecde0-0dc0-4f9b-a9c8-aa8b4b741aae',
    'vocabulary_machine_name' => 'company_type',
  );
  $terms[] = array(
    'name' => 'e-PRO',
    'description' => 'e-PRO® Electronic Certified Professional',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b8a1ec81-807c-4068-98e0-88c5fb7c194a',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'NH',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ba75e6cb-2eb1-4da1-b241-e103052685d1',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'Guest',
    'description' => 'Guest members may save listings for future reference',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'bc501392-6744-40b3-a091-1384ead36991',
    'vocabulary_machine_name' => 'company_type',
  );
  $terms[] = array(
    'name' => 'AQUITAINE',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bcb931f1-ed59-4374-ad28-4646452631d9',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'WLG',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c22b5355-4bf7-47d2-bc1b-fdb6d636b5ac',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'CCIM',
    'description' => 'Certified Commercial Investment Member / CCIM(sm)',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c323cb43-3fe1-4856-9211-6bea6934678f',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'BB',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c40d2afa-2675-4acd-9c98-072277fffe4a',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'ZH',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c7c651d4-aad3-4511-8ed8-6ed79f9f7ea5',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'MD',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c7c7224c-14f6-4847-a86d-7636f931cc61',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'GREEN',
    'description' => 'NARs Green Designation / GREEN',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c9792e6e-2620-48ef-bc91-ed523ed16956',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'FL',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cc6734c7-ff32-49c0-86d2-a5be93569fd6',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'MA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cf3182d3-6470-4d36-a5e1-b21c5d58297e',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'SA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd0b71a8d-a6b7-4bad-b5f0-b1715ffdc7f9',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'TAS',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd7df8e91-8a23-4b0f-b4be-50da86bee494',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'SN',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'df43fbf6-79f1-4801-a542-4c7fbcf95c3b',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'Website',
    'description' => 'Domain registration, website design and development, hosting',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => 'e7e8c1a4-67bd-4fa6-9d65-49005f525542',
    'vocabulary_machine_name' => 'company_type',
  );
  $terms[] = array(
    'name' => 'PA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e852f74f-5c91-471a-bdc8-a92ccc51e269',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'ABR',
    'description' => 'Accredited Buyers Representative',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'efa4a551-4ff2-4c45-a507-d34e44b03a66',
    'vocabulary_machine_name' => 'designations',
  );
  $terms[] = array(
    'name' => 'GA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f1e43f5e-3900-429a-887a-01197391c774',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  $terms[] = array(
    'name' => 'VIC',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fb6d8a6c-1b74-4828-92dc-f0aebab9aa0e',
    'vocabulary_machine_name' => 'licensed_state_',
  );
  return $terms;
}
